### PR TITLE
Cleaning up monsterPathfind function

### PR DESCRIPTION
**Pull request by KiyoNetcat**

### CODE REVIEW

**Comment by ghost** [comment]
No

**Comment by KiyoNetcat** [comment]
This is a lot easier to read, understand, and debug. This would also be less overhead, as it only calls Math.pow() twice and Math.sqrt() once, as opposed to calling Math.pow() 6 times.

**Review by MC-Atom — CHANGES_REQUESTED** [review]
Hey, quick thing, Math.pow should be replaced by **2 because it's slightly fewer calls and it can stackup when the pathfinding thing gets big and it helps parsibility. You can change sqrt to ** 0.5, too, but I'd say the slight speed isn't worth the parsibility, so it really doesn't matter. Ur choice

**Review by MC-Atom — APPROVED** [review]
Looks Good!

**Pull request merged**
